export interface CapitalInfo {
  capitalRu: string;
  capitalEn: string;
  alt?: string[]; // lowercase alternative spellings (both languages)
}

export const CAPITALS: Record<string, CapitalInfo> = {
  // ── EUROPE ──
  de: { capitalRu: "Берлин",              capitalEn: "Berlin" },
  fr: { capitalRu: "Париж",               capitalEn: "Paris" },
  it: { capitalRu: "Рим",                 capitalEn: "Rome",             alt: ["roma"] },
  es: { capitalRu: "Мадрид",              capitalEn: "Madrid" },
  pt: { capitalRu: "Лиссабон",            capitalEn: "Lisbon",           alt: ["lisboa"] },
  nl: { capitalRu: "Амстердам",           capitalEn: "Amsterdam",        alt: ["гаага", "the hague"] },
  be: { capitalRu: "Брюссель",            capitalEn: "Brussels",         alt: ["bruxelles", "brussel"] },
  at: { capitalRu: "Вена",               capitalEn: "Vienna",           alt: ["wien"] },
  ch: { capitalRu: "Берн",               capitalEn: "Bern",             alt: ["berne"] },
  se: { capitalRu: "Стокгольм",           capitalEn: "Stockholm" },
  no: { capitalRu: "Осло",               capitalEn: "Oslo" },
  dk: { capitalRu: "Копенгаген",          capitalEn: "Copenhagen",       alt: ["københavn"] },
  fi: { capitalRu: "Хельсинки",           capitalEn: "Helsinki",         alt: ["helsingfors"] },
  pl: { capitalRu: "Варшава",             capitalEn: "Warsaw",           alt: ["warszawa"] },
  cz: { capitalRu: "Прага",              capitalEn: "Prague",           alt: ["praha"] },
  ua: { capitalRu: "Киев",               capitalEn: "Kyiv",             alt: ["kiev"] },
  ro: { capitalRu: "Бухарест",            capitalEn: "Bucharest",        alt: ["bucurești"] },
  gr: { capitalRu: "Афины",              capitalEn: "Athens",           alt: ["athina"] },
  tr: { capitalRu: "Анкара",             capitalEn: "Ankara" },
  gb: { capitalRu: "Лондон",             capitalEn: "London" },
  ie: { capitalRu: "Дублин",             capitalEn: "Dublin" },
  is: { capitalRu: "Рейкьявик",           capitalEn: "Reykjavik",        alt: ["reykjavík"] },
  hu: { capitalRu: "Будапешт",            capitalEn: "Budapest" },
  hr: { capitalRu: "Загреб",             capitalEn: "Zagreb" },
  rs: { capitalRu: "Белград",             capitalEn: "Belgrade",         alt: ["beograd"] },
  si: { capitalRu: "Любляна",             capitalEn: "Ljubljana" },
  sk: { capitalRu: "Братислава",          capitalEn: "Bratislava" },
  me: { capitalRu: "Подгорица",           capitalEn: "Podgorica" },
  mt: { capitalRu: "Валлетта",            capitalEn: "Valletta" },
  ee: { capitalRu: "Таллин",             capitalEn: "Tallinn" },
  lv: { capitalRu: "Рига",              capitalEn: "Riga" },
  lt: { capitalRu: "Вильнюс",             capitalEn: "Vilnius" },
  ru: { capitalRu: "Москва",             capitalEn: "Moscow",           alt: ["moskva"] },
  bg: { capitalRu: "София",              capitalEn: "Sofia",            alt: ["sofiya"] },
  al: { capitalRu: "Тирана",             capitalEn: "Tirana",           alt: ["tiranë"] },
  ba: { capitalRu: "Сараево",             capitalEn: "Sarajevo" },
  by: { capitalRu: "Минск",              capitalEn: "Minsk" },
  cy: { capitalRu: "Никосия",             capitalEn: "Nicosia",          alt: ["lefkosia"] },
  lu: { capitalRu: "Люксембург",          capitalEn: "Luxembourg City",  alt: ["luxembourg"] },
  md: { capitalRu: "Кишинёв",             capitalEn: "Chisinau",         alt: ["chișinău", "кишинев", "kishinev"] },
  mc: { capitalRu: "Монако",             capitalEn: "Monaco" },
  mk: { capitalRu: "Скопье",             capitalEn: "Skopje" },
  ad: { capitalRu: "Андорра-ла-Велья",    capitalEn: "Andorra la Vella", alt: ["андорра", "andorra"] },
  li: { capitalRu: "Вадуц",              capitalEn: "Vaduz" },
  sm: { capitalRu: "Сан-Марино",          capitalEn: "San Marino" },
  va: { capitalRu: "Ватикан",             capitalEn: "Vatican City",     alt: ["vatican"] },
  xk: { capitalRu: "Приштина",            capitalEn: "Pristina",         alt: ["prishtina", "prishtinë"] },

  // ── ASIA ──
  jp: { capitalRu: "Токио",              capitalEn: "Tokyo" },
  kr: { capitalRu: "Сеул",              capitalEn: "Seoul" },
  cn: { capitalRu: "Пекин",             capitalEn: "Beijing",          alt: ["peking"] },
  th: { capitalRu: "Бангкок",            capitalEn: "Bangkok" },
  vn: { capitalRu: "Ханой",             capitalEn: "Hanoi",            alt: ["hà nội"] },
  id: { capitalRu: "Джакарта",           capitalEn: "Jakarta" },
  in: { capitalRu: "Нью-Дели",           capitalEn: "New Delhi",        alt: ["дели", "delhi"] },
  ae: { capitalRu: "Абу-Даби",           capitalEn: "Abu Dhabi" },
  sg: { capitalRu: "Сингапур",           capitalEn: "Singapore" },
  my: { capitalRu: "Куала-Лумпур",       capitalEn: "Kuala Lumpur" },
  ph: { capitalRu: "Манила",             capitalEn: "Manila" },
  lk: { capitalRu: "Шри-Джаяварденепура-Котте", capitalEn: "Sri Jayawardenepura Kotte", alt: ["коломбо", "colombo", "котте", "kotte"] },
  np: { capitalRu: "Катманду",           capitalEn: "Kathmandu",        alt: ["katmandu"] },
  ge: { capitalRu: "Тбилиси",            capitalEn: "Tbilisi" },
  am: { capitalRu: "Ереван",             capitalEn: "Yerevan" },
  az: { capitalRu: "Баку",              capitalEn: "Baku" },
  il: { capitalRu: "Иерусалим",          capitalEn: "Jerusalem",        alt: ["тель-авив", "tel aviv"] },
  jo: { capitalRu: "Амман",             capitalEn: "Amman" },
  uz: { capitalRu: "Ташкент",            capitalEn: "Tashkent" },
  kz: { capitalRu: "Астана",             capitalEn: "Astana",           alt: ["нур-султан", "nur-sultan", "нурсултан"] },
  mn: { capitalRu: "Улан-Батор",         capitalEn: "Ulaanbaatar",      alt: ["ulan bator"] },
  kh: { capitalRu: "Пномпень",           capitalEn: "Phnom Penh" },
  mv: { capitalRu: "Мале",              capitalEn: "Malé",             alt: ["male"] },
  sa: { capitalRu: "Эр-Рияд",            capitalEn: "Riyadh",           alt: ["рияд"] },
  qa: { capitalRu: "Доха",              capitalEn: "Doha" },
  bh: { capitalRu: "Манама",             capitalEn: "Manama" },
  kw: { capitalRu: "Эль-Кувейт",         capitalEn: "Kuwait City",      alt: ["кувейт", "kuwait"] },
  om: { capitalRu: "Маскат",             capitalEn: "Muscat" },
  lb: { capitalRu: "Бейрут",             capitalEn: "Beirut" },
  sy: { capitalRu: "Дамаск",             capitalEn: "Damascus",         alt: ["dimashq"] },
  iq: { capitalRu: "Багдад",             capitalEn: "Baghdad" },
  ir: { capitalRu: "Тегеран",            capitalEn: "Tehran" },
  pk: { capitalRu: "Исламабад",          capitalEn: "Islamabad" },
  bd: { capitalRu: "Дакка",             capitalEn: "Dhaka",            alt: ["dacca"] },
  bt: { capitalRu: "Тхимпху",            capitalEn: "Thimphu",          alt: ["thimbu"] },
  mm: { capitalRu: "Нейпьидо",           capitalEn: "Naypyidaw",        alt: ["nay pyi taw", "нэпьидо"] },
  la: { capitalRu: "Вьентьян",           capitalEn: "Vientiane" },
  bn: { capitalRu: "Бандар-Сери-Бегаван", capitalEn: "Bandar Seri Begawan", alt: ["бандар сери бегаван"] },
  tw: { capitalRu: "Тайбэй",             capitalEn: "Taipei" },
  kg: { capitalRu: "Бишкек",             capitalEn: "Bishkek" },
  tj: { capitalRu: "Душанбе",            capitalEn: "Dushanbe" },
  tm: { capitalRu: "Ашхабад",            capitalEn: "Ashgabat",         alt: ["ashkhabad", "ашгабад"] },
  af: { capitalRu: "Кабул",             capitalEn: "Kabul" },
  ye: { capitalRu: "Сана",              capitalEn: "Sana'a",           alt: ["sanaa", "санаа"] },
  kp: { capitalRu: "Пхеньян",            capitalEn: "Pyongyang" },
  tl: { capitalRu: "Дили",              capitalEn: "Dili" },

  // ── NORTH AMERICA ──
  us: { capitalRu: "Вашингтон",          capitalEn: "Washington D.C.",  alt: ["washington", "вашингтон д.к."] },
  ca: { capitalRu: "Оттава",             capitalEn: "Ottawa" },
  mx: { capitalRu: "Мехико",             capitalEn: "Mexico City",      alt: ["mexico", "мексика"] },
  cu: { capitalRu: "Гавана",             capitalEn: "Havana",           alt: ["la habana"] },
  cr: { capitalRu: "Сан-Хосе",           capitalEn: "San José",         alt: ["san jose"] },
  pa: { capitalRu: "Панама",             capitalEn: "Panama City",      alt: ["panama"] },
  do: { capitalRu: "Санто-Доминго",      capitalEn: "Santo Domingo" },
  jm: { capitalRu: "Кингстон",           capitalEn: "Kingston" },
  gt: { capitalRu: "Гватемала",          capitalEn: "Guatemala City",   alt: ["guatemala"] },
  bs: { capitalRu: "Нассау",             capitalEn: "Nassau" },
  bb: { capitalRu: "Бриджтаун",          capitalEn: "Bridgetown" },
  bz: { capitalRu: "Бельмопан",          capitalEn: "Belmopan" },
  sv: { capitalRu: "Сан-Сальвадор",      capitalEn: "San Salvador" },
  hn: { capitalRu: "Тегусигальпа",       capitalEn: "Tegucigalpa" },
  ni: { capitalRu: "Манагуа",            capitalEn: "Managua" },
  ht: { capitalRu: "Порт-о-Пренс",       capitalEn: "Port-au-Prince",   alt: ["port au prince"] },
  tt: { capitalRu: "Порт-оф-Спейн",      capitalEn: "Port of Spain",    alt: ["port-of-spain"] },
  ag: { capitalRu: "Сент-Джонс",         capitalEn: "Saint John's",     alt: ["st. john's", "st johns"] },
  gd: { capitalRu: "Сент-Джорджес",      capitalEn: "St. George's",     alt: ["saint george's", "st georges"] },
  lc: { capitalRu: "Кастри",             capitalEn: "Castries" },
  vc: { capitalRu: "Кингстаун",          capitalEn: "Kingstown" },
  kn: { capitalRu: "Бастер",             capitalEn: "Basseterre" },

  // ── SOUTH AMERICA ──
  br: { capitalRu: "Бразилиа",           capitalEn: "Brasília",         alt: ["brasilia", "бразилия"] },
  ar: { capitalRu: "Буэнос-Айрес",       capitalEn: "Buenos Aires" },
  cl: { capitalRu: "Сантьяго",           capitalEn: "Santiago" },
  pe: { capitalRu: "Лима",              capitalEn: "Lima" },
  co: { capitalRu: "Богота",             capitalEn: "Bogotá",           alt: ["bogota"] },
  bo: { capitalRu: "Сукре",             capitalEn: "Sucre",            alt: ["la paz", "ла-пас"] },
  ec: { capitalRu: "Кито",              capitalEn: "Quito" },
  uy: { capitalRu: "Монтевидео",         capitalEn: "Montevideo" },
  ve: { capitalRu: "Каракас",            capitalEn: "Caracas" },
  py: { capitalRu: "Асунсьон",           capitalEn: "Asunción",         alt: ["asuncion"] },
  gy: { capitalRu: "Джорджтаун",         capitalEn: "Georgetown" },
  sr: { capitalRu: "Парамарибо",         capitalEn: "Paramaribo" },

  // ── AFRICA ──
  eg: { capitalRu: "Каир",              capitalEn: "Cairo",            alt: ["al-qahira"] },
  ma: { capitalRu: "Рабат",             capitalEn: "Rabat" },
  za: { capitalRu: "Претория",           capitalEn: "Pretoria",         alt: ["cape town", "кейптаун", "bloemfontein"] },
  tz: { capitalRu: "Додома",             capitalEn: "Dodoma",           alt: ["дар-эс-салам", "dar es salaam"] },
  ke: { capitalRu: "Найроби",            capitalEn: "Nairobi" },
  tn: { capitalRu: "Тунис",             capitalEn: "Tunis" },
  et: { capitalRu: "Аддис-Абеба",        capitalEn: "Addis Ababa",      alt: ["addis abeba"] },
  ng: { capitalRu: "Абуджа",             capitalEn: "Abuja" },
  mu: { capitalRu: "Порт-Луи",           capitalEn: "Port Louis" },
  sc: { capitalRu: "Виктория",           capitalEn: "Victoria" },
  na: { capitalRu: "Виндхук",            capitalEn: "Windhoek" },
  dz: { capitalRu: "Алжир",             capitalEn: "Algiers",          alt: ["alger"] },
  gh: { capitalRu: "Аккра",             capitalEn: "Accra" },
  sn: { capitalRu: "Дакар",             capitalEn: "Dakar" },
  ci: { capitalRu: "Ямусукро",           capitalEn: "Yamoussoukro",     alt: ["абиджан", "abidjan"] },
  cm: { capitalRu: "Яунде",             capitalEn: "Yaoundé",          alt: ["yaounde"] },
  ao: { capitalRu: "Луанда",             capitalEn: "Luanda" },
  zw: { capitalRu: "Хараре",             capitalEn: "Harare" },
  zm: { capitalRu: "Лусака",             capitalEn: "Lusaka" },
  ug: { capitalRu: "Кампала",            capitalEn: "Kampala" },
  rw: { capitalRu: "Кигали",             capitalEn: "Kigali" },
  mz: { capitalRu: "Мапуту",             capitalEn: "Maputo" },
  mg: { capitalRu: "Антананариву",       capitalEn: "Antananarivo" },
  bw: { capitalRu: "Габороне",           capitalEn: "Gaborone" },
  cv: { capitalRu: "Прая",              capitalEn: "Praia" },
  bi: { capitalRu: "Гитега",             capitalEn: "Gitega",           alt: ["bujumbura", "бужумбура"] },
  ml: { capitalRu: "Бамако",             capitalEn: "Bamako" },
  bf: { capitalRu: "Уагадугу",           capitalEn: "Ouagadougou" },
  ne: { capitalRu: "Ниамей",             capitalEn: "Niamey" },
  td: { capitalRu: "Нджамена",           capitalEn: "N'Djamena",        alt: ["ndjamena"] },
  sd: { capitalRu: "Хартум",             capitalEn: "Khartoum" },
  ss: { capitalRu: "Джуба",             capitalEn: "Juba" },
  so: { capitalRu: "Могадишо",           capitalEn: "Mogadishu",        alt: ["muqdisho"] },
  er: { capitalRu: "Асмэра",             capitalEn: "Asmara",           alt: ["асмара"] },
  dj: { capitalRu: "Джибути",            capitalEn: "Djibouti City",    alt: ["djibouti"] },
  sz: { capitalRu: "Мбабане",            capitalEn: "Mbabane" },
  ls: { capitalRu: "Масеру",             capitalEn: "Maseru" },
  ly: { capitalRu: "Триполи",            capitalEn: "Tripoli" },
  mw: { capitalRu: "Лилонгве",           capitalEn: "Lilongwe" },
  mr: { capitalRu: "Нуакшот",            capitalEn: "Nouakchott" },
  gm: { capitalRu: "Банджул",            capitalEn: "Banjul" },
  sl: { capitalRu: "Фритаун",            capitalEn: "Freetown" },
  lr: { capitalRu: "Монровия",           capitalEn: "Monrovia" },
  gn: { capitalRu: "Конакри",            capitalEn: "Conakry" },
  gw: { capitalRu: "Бисау",             capitalEn: "Bissau" },
  bj: { capitalRu: "Порто-Ново",         capitalEn: "Porto-Novo",       alt: ["котону", "cotonou"] },
  tg: { capitalRu: "Ломе",              capitalEn: "Lomé",             alt: ["lome"] },
  cf: { capitalRu: "Банги",             capitalEn: "Bangui" },
  cd: { capitalRu: "Киншаса",            capitalEn: "Kinshasa" },
  cg: { capitalRu: "Браззавиль",         capitalEn: "Brazzaville" },
  ga: { capitalRu: "Либревиль",          capitalEn: "Libreville" },
  gq: { capitalRu: "Малабо",             capitalEn: "Malabo" },
  st: { capitalRu: "Сан-Томе",           capitalEn: "São Tomé",         alt: ["sao tome"] },
  km: { capitalRu: "Морони",             capitalEn: "Moroni" },

  // ── OCEANIA ──
  au: { capitalRu: "Канберра",           capitalEn: "Canberra" },
  nz: { capitalRu: "Веллингтон",         capitalEn: "Wellington" },
  fj: { capitalRu: "Сува",              capitalEn: "Suva" },
  pf: { capitalRu: "Папеэте",            capitalEn: "Papeete" },
  ws: { capitalRu: "Апиа",              capitalEn: "Apia" },
  pg: { capitalRu: "Порт-Морсби",        capitalEn: "Port Moresby" },
  sb: { capitalRu: "Хониара",            capitalEn: "Honiara" },
  vu: { capitalRu: "Порт-Вила",          capitalEn: "Port Vila" },
  to: { capitalRu: "Нукуалофа",          capitalEn: "Nukuʻalofa",       alt: ["nukualofa"] },
  ki: { capitalRu: "Тарава",             capitalEn: "South Tarawa",     alt: ["tarawa"] },
  fm: { capitalRu: "Паликир",            capitalEn: "Palikir" },
  mh: { capitalRu: "Маджуро",            capitalEn: "Majuro" },
  pw: { capitalRu: "Нгерулмуд",          capitalEn: "Ngerulmud",        alt: ["мелекеок", "koror", "корор"] },
  nr: { capitalRu: "Ярен",              capitalEn: "Yaren" },
  tv: { capitalRu: "Фунафути",           capitalEn: "Funafuti" },
  ck: { capitalRu: "Аваруа",             capitalEn: "Avarua" },
};
