import type { Country } from "./types";

export const COUNTRIES: Country[] = [
  // ─────────── EUROPE ───────────
  { code: "de", nameRu: "Германия", nameEn: "Germany", flag: "🇩🇪", region: "europe", symbol: "🏛️", landmark: "Бранденбургские ворота, Чёрный лес", accent: ["#1f2937", "#b91c1c"], motif: "gate" },
  { code: "fr", nameRu: "Франция", nameEn: "France", flag: "🇫🇷", region: "europe", symbol: "🗼", landmark: "Эйфелева башня, Лазурный берег", accent: ["#1e3a8a", "#9333ea"], motif: "tower" },
  { code: "it", nameRu: "Италия", nameEn: "Italy", flag: "🇮🇹", region: "europe", symbol: "🏟️", landmark: "Колизей, Венеция, Тоскана", accent: ["#15803d", "#b91c1c"], motif: "arena" },
  { code: "es", nameRu: "Испания", nameEn: "Spain", flag: "🇪🇸", region: "europe", symbol: "💃", landmark: "Саграда Фамилия, фламенко", accent: ["#b91c1c", "#f59e0b"], motif: "flame" },
  { code: "pt", nameRu: "Португалия", nameEn: "Portugal", flag: "🇵🇹", region: "europe", symbol: "⛵", landmark: "Лиссабон, трамваи, океан", accent: ["#065f46", "#dc2626"], motif: "wave" },
  { code: "nl", nameRu: "Нидерланды", nameEn: "Netherlands", flag: "🇳🇱", region: "europe", symbol: "🌷", landmark: "Каналы Амстердама, тюльпаны", accent: ["#ea580c", "#1d4ed8"], motif: "tulip" },
  { code: "be", nameRu: "Бельгия", nameEn: "Belgium", flag: "🇧🇪", region: "europe", symbol: "🍫", landmark: "Брюссель, шоколад, вафли", accent: ["#1f2937", "#eab308"], motif: "spark" },
  { code: "at", nameRu: "Австрия", nameEn: "Austria", flag: "🇦🇹", region: "europe", symbol: "🎻", landmark: "Вена, Альпы, музыка", accent: ["#b91c1c", "#f8fafc"], motif: "note" },
  { code: "ch", nameRu: "Швейцария", nameEn: "Switzerland", flag: "🇨🇭", region: "europe", symbol: "🏔️", landmark: "Альпы, Маттерхорн, озёра", accent: ["#dc2626", "#e2e8f0"], motif: "peak" },
  { code: "se", nameRu: "Швеция", nameEn: "Sweden", flag: "🇸🇪", region: "europe", symbol: "🌌", landmark: "Стокгольм, северное сияние", accent: ["#1d4ed8", "#22d3ee"], motif: "aurora" },
  { code: "no", nameRu: "Норвегия", nameEn: "Norway", flag: "🇳🇴", region: "europe", symbol: "⛰️", landmark: "Фьорды, северное сияние", accent: ["#1e3a8a", "#14b8a6"], motif: "fjord" },
  { code: "dk", nameRu: "Дания", nameEn: "Denmark", flag: "🇩🇰", region: "europe", symbol: "🧜", landmark: "Копенгаген, Нюхавн", accent: ["#b91c1c", "#fb7185"], motif: "spark" },
  { code: "fi", nameRu: "Финляндия", nameEn: "Finland", flag: "🇫🇮", region: "europe", symbol: "❄️", landmark: "Тысяча озёр, сауна, Лапландия", accent: ["#0ea5e9", "#f1f5f9"], motif: "snow" },
  { code: "pl", nameRu: "Польша", nameEn: "Poland", flag: "🇵🇱", region: "europe", symbol: "🏰", landmark: "Краков, Варшава", accent: ["#dc2626", "#f8fafc"], motif: "castle" },
  { code: "cz", nameRu: "Чехия", nameEn: "Czech Republic", flag: "🇨🇿", region: "europe", symbol: "🍺", landmark: "Прага, Карлов мост", accent: ["#1d4ed8", "#dc2626"], motif: "bridge" },
  { code: "ua", nameRu: "Украина", nameEn: "Ukraine", flag: "🇺🇦", region: "europe", symbol: "🌻", landmark: "Киев, пшеничные поля", accent: ["#0057b7", "#ffd700"], motif: "wheat" },
  { code: "ro", nameRu: "Румыния", nameEn: "Romania", flag: "🇷🇴", region: "europe", symbol: "🏰", landmark: "Замок Бран, Карпаты", accent: ["#1e3a8a", "#7c2d12"], motif: "castle" },
  { code: "gr", nameRu: "Греция", nameEn: "Greece", flag: "🇬🇷", region: "europe", symbol: "🏛️", landmark: "Акрополь, Санторини", accent: ["#1d4ed8", "#e0f2fe"], motif: "column" },
  { code: "tr", nameRu: "Турция", nameEn: "Turkey", flag: "🇹🇷", region: "europe", symbol: "🕌", landmark: "Стамбул, Каппадокия", accent: ["#b91c1c", "#f59e0b"], motif: "balloon" },
  { code: "gb", nameRu: "Великобритания", nameEn: "United Kingdom", flag: "🇬🇧", region: "europe", symbol: "🎡", landmark: "Биг-Бен, Лондонский глаз", accent: ["#1e3a8a", "#dc2626"], motif: "clock" },
  { code: "ie", nameRu: "Ирландия", nameEn: "Ireland", flag: "🇮🇪", region: "europe", symbol: "🍀", landmark: "Изумрудный остров, утёсы", accent: ["#15803d", "#f59e0b"], motif: "clover" },
  { code: "is", nameRu: "Исландия", nameEn: "Iceland", flag: "🇮🇸", region: "europe", symbol: "🌋", landmark: "Гейзеры, вулканы, сияние", accent: ["#0f766e", "#a5f3fc"], motif: "aurora" },
  { code: "hu", nameRu: "Венгрия", nameEn: "Hungary", flag: "🇭🇺", region: "europe", symbol: "🌉", landmark: "Будапешт, купальни", accent: ["#dc2626", "#15803d"], motif: "bridge" },
  { code: "hr", nameRu: "Хорватия", nameEn: "Croatia", flag: "🇭🇷", region: "europe", symbol: "🏖️", landmark: "Дубровник, Адриатика", accent: ["#1d4ed8", "#dc2626"], motif: "wave" },
  { code: "rs", nameRu: "Сербия", nameEn: "Serbia", flag: "🇷🇸", region: "europe", symbol: "🏰", landmark: "Белград, Дунай", accent: ["#1e3a8a", "#b91c1c"], motif: "castle" },
  { code: "si", nameRu: "Словения", nameEn: "Slovenia", flag: "🇸🇮", region: "europe", symbol: "🏞️", landmark: "Озеро Блед, Альпы", accent: ["#0f766e", "#38bdf8"], motif: "peak" },
  { code: "sk", nameRu: "Словакия", nameEn: "Slovakia", flag: "🇸🇰", region: "europe", symbol: "⛰️", landmark: "Татры, Братислава", accent: ["#1d4ed8", "#dc2626"], motif: "peak" },
  { code: "me", nameRu: "Черногория", nameEn: "Montenegro", flag: "🇲🇪", region: "europe", symbol: "⛵", landmark: "Котор, Адриатика", accent: ["#7c2d12", "#dc2626"], motif: "wave" },
  { code: "mt", nameRu: "Мальта", nameEn: "Malta", flag: "🇲🇹", region: "europe", symbol: "🏖️", landmark: "Валлетта, лазурное море", accent: ["#dc2626", "#f8fafc"], motif: "wave" },
  { code: "ee", nameRu: "Эстония", nameEn: "Estonia", flag: "🇪🇪", region: "europe", symbol: "🏰", landmark: "Таллин, старый город", accent: ["#0ea5e9", "#1f2937"], motif: "castle" },
  { code: "lv", nameRu: "Латвия", nameEn: "Latvia", flag: "🇱🇻", region: "europe", symbol: "🌲", landmark: "Рига, ар-нуво", accent: ["#7f1d1d", "#dc2626"], motif: "spark" },
  { code: "lt", nameRu: "Литва", nameEn: "Lithuania", flag: "🇱🇹", region: "europe", symbol: "🌟", landmark: "Вильнюс, янтарь", accent: ["#eab308", "#15803d"], motif: "spark" },
  { code: "ru", nameRu: "Россия", nameEn: "Russia", flag: "🇷🇺", region: "europe", symbol: "🏛️", landmark: "Красная площадь, Байкал", accent: ["#1e3a8a", "#dc2626"], motif: "castle" },
  { code: "bg", nameRu: "Болгария", nameEn: "Bulgaria", flag: "🇧🇬", region: "europe", symbol: "🌹", landmark: "Старый Несебыр, горы", accent: ["#15803d", "#f8fafc"], motif: "spark" },
  { code: "al", nameRu: "Албания", nameEn: "Albania", flag: "🇦🇱", region: "europe", symbol: "🦅", landmark: "Ривьера, горные деревни", accent: ["#b91c1c", "#f8fafc"], motif: "peak" },
  { code: "ba", nameRu: "Босния и Герцеговина", nameEn: "Bosnia and Herzegovina", flag: "🇧🇦", region: "europe", symbol: "🌉", landmark: "Сараево, Мостарский мост", accent: ["#1e3a8a", "#eab308"], motif: "bridge" },
  { code: "by", nameRu: "Беларусь", nameEn: "Belarus", flag: "🇧🇾", region: "europe", symbol: "🌲", landmark: "Минск, беловежская пуща", accent: ["#dc2626", "#15803d"], motif: "spark" },
  { code: "cy", nameRu: "Кипр", nameEn: "Cyprus", flag: "🇨🇾", region: "europe", symbol: "🏛️", landmark: "Пафос, Лимасол, пляжи", accent: ["#0ea5e9", "#eab308"], motif: "column" },
  { code: "lu", nameRu: "Люксембург", nameEn: "Luxembourg", flag: "🇱🇺", region: "europe", symbol: "🏰", landmark: "Люксембургская крепость", accent: ["#dc2626", "#0ea5e9"], motif: "castle" },
  { code: "md", nameRu: "Молдова", nameEn: "Moldova", flag: "🇲🇩", region: "europe", symbol: "🍷", landmark: "Кишинёв, винные погреба", accent: ["#1e3a8a", "#eab308"], motif: "spark" },
  { code: "mc", nameRu: "Монако", nameEn: "Monaco", flag: "🇲🇨", region: "europe", symbol: "🏎️", landmark: "Монте-Карло, Формула-1", accent: ["#b91c1c", "#f8fafc"], motif: "spark" },
  { code: "mk", nameRu: "Северная Македония", nameEn: "North Macedonia", flag: "🇲🇰", region: "europe", symbol: "🏛️", landmark: "Охридское озеро, Скопье", accent: ["#eab308", "#dc2626"], motif: "column" },
  { code: "ad", nameRu: "Андорра", nameEn: "Andorra", flag: "🇦🇩", region: "europe", symbol: "⛷️", landmark: "Пиренеи, горнолыжные курорты", accent: ["#1e3a8a", "#eab308"], motif: "peak" },
  { code: "li", nameRu: "Лихтенштейн", nameEn: "Liechtenstein", flag: "🇱🇮", region: "europe", symbol: "🏰", landmark: "Вадуц, Рейнская долина", accent: ["#1e3a8a", "#dc2626"], motif: "castle" },
  { code: "sm", nameRu: "Сан-Марино", nameEn: "San Marino", flag: "🇸🇲", region: "europe", symbol: "🏰", landmark: "Крепость на вершине горы", accent: ["#22d3ee", "#f8fafc"], motif: "castle" },
  { code: "va", nameRu: "Ватикан", nameEn: "Vatican", flag: "🇻🇦", region: "europe", symbol: "⛪", landmark: "Собор Святого Петра, Сикстина", accent: ["#eab308", "#f8fafc"], motif: "temple" },
  { code: "xk", nameRu: "Косово", nameEn: "Kosovo", flag: "🇽🇰", region: "europe", symbol: "🕌", landmark: "Приштина, православные монастыри", accent: ["#1d4ed8", "#eab308"], motif: "castle" },

  // ─────────── ASIA ───────────
  { code: "jp", nameRu: "Япония", nameEn: "Japan", flag: "🇯🇵", region: "asia", symbol: "🗻", landmark: "Фудзи, Токио, сакура", accent: ["#be123c", "#fda4af"], motif: "sakura" },
  { code: "kr", nameRu: "Южная Корея", nameEn: "South Korea", flag: "🇰🇷", region: "asia", symbol: "🏯", landmark: "Сеул, дворцы, K-pop", accent: ["#1d4ed8", "#dc2626"], motif: "spark" },
  { code: "cn", nameRu: "Китай", nameEn: "China", flag: "🇨🇳", region: "asia", symbol: "🏯", landmark: "Великая стена, Пекин", accent: ["#b91c1c", "#f59e0b"], motif: "wall" },
  { code: "th", nameRu: "Таиланд", nameEn: "Thailand", flag: "🇹🇭", region: "asia", symbol: "🛕", landmark: "Бангкок, храмы, пляжи", accent: ["#0e7490", "#f59e0b"], motif: "temple" },
  { code: "vn", nameRu: "Вьетнам", nameEn: "Vietnam", flag: "🇻🇳", region: "asia", symbol: "⛩️", landmark: "Халонг, рисовые террасы", accent: ["#b91c1c", "#eab308"], motif: "wave" },
  { code: "id", nameRu: "Индонезия", nameEn: "Indonesia", flag: "🇮🇩", region: "asia", symbol: "🌴", landmark: "Бали, вулканы, рисовые поля", accent: ["#dc2626", "#0d9488"], motif: "leaf" },
  { code: "in", nameRu: "Индия", nameEn: "India", flag: "🇮🇳", region: "asia", symbol: "🕌", landmark: "Тадж-Махал, специи", accent: ["#ea580c", "#15803d"], motif: "temple" },
  { code: "ae", nameRu: "ОАЭ", nameEn: "UAE", flag: "🇦🇪", region: "asia", symbol: "🏙️", landmark: "Дубай, Бурдж-Халифа", accent: ["#854d0e", "#fde68a"], motif: "tower" },
  { code: "sg", nameRu: "Сингапур", nameEn: "Singapore", flag: "🇸🇬", region: "asia", symbol: "🌃", landmark: "Marina Bay, сады будущего", accent: ["#0f766e", "#22d3ee"], motif: "tower" },
  { code: "my", nameRu: "Малайзия", nameEn: "Malaysia", flag: "🇲🇾", region: "asia", symbol: "🌆", landmark: "Башни Петронас, Куала-Лумпур", accent: ["#1e3a8a", "#0d9488"], motif: "tower" },
  { code: "ph", nameRu: "Филиппины", nameEn: "Philippines", flag: "🇵🇭", region: "asia", symbol: "🏝️", landmark: "7000 островов, лагуны", accent: ["#1d4ed8", "#22d3ee"], motif: "wave" },
  { code: "lk", nameRu: "Шри-Ланка", nameEn: "Sri Lanka", flag: "🇱🇰", region: "asia", symbol: "🐘", landmark: "Чайные плантации, храмы", accent: ["#854d0e", "#15803d"], motif: "leaf" },
  { code: "np", nameRu: "Непал", nameEn: "Nepal", flag: "🇳🇵", region: "asia", symbol: "🏔️", landmark: "Эверест, Гималаи", accent: ["#7c2d12", "#e0f2fe"], motif: "peak" },
  { code: "ge", nameRu: "Грузия", nameEn: "Georgia", flag: "🇬🇪", region: "asia", symbol: "🍇", landmark: "Тбилиси, Кавказ, вино", accent: ["#b91c1c", "#0f766e"], motif: "peak" },
  { code: "am", nameRu: "Армения", nameEn: "Armenia", flag: "🇦🇲", region: "asia", symbol: "⛰️", landmark: "Арарат, монастыри", accent: ["#b91c1c", "#1d4ed8"], motif: "peak" },
  { code: "az", nameRu: "Азербайджан", nameEn: "Azerbaijan", flag: "🇦🇿", region: "asia", symbol: "🔥", landmark: "Баку, огненные башни", accent: ["#0d9488", "#f59e0b"], motif: "flame" },
  { code: "il", nameRu: "Израиль", nameEn: "Israel", flag: "🇮🇱", region: "asia", symbol: "🕍", landmark: "Иерусалим, Мёртвое море", accent: ["#1d4ed8", "#e0f2fe"], motif: "temple" },
  { code: "jo", nameRu: "Иордания", nameEn: "Jordan", flag: "🇯🇴", region: "asia", symbol: "🏜️", landmark: "Петра, Вади-Рам", accent: ["#9a3412", "#fbbf24"], motif: "sand" },
  { code: "uz", nameRu: "Узбекистан", nameEn: "Uzbekistan", flag: "🇺🇿", region: "asia", symbol: "🕌", landmark: "Самарканд, Шёлковый путь", accent: ["#0e7490", "#f59e0b"], motif: "temple" },
  { code: "kz", nameRu: "Казахстан", nameEn: "Kazakhstan", flag: "🇰🇿", region: "asia", symbol: "🏙️", landmark: "Астана, степи", accent: ["#0ea5e9", "#fde047"], motif: "tower" },
  { code: "mn", nameRu: "Монголия", nameEn: "Mongolia", flag: "🇲🇳", region: "asia", symbol: "🐎", landmark: "Степи, юрты, Чингисхан", accent: ["#b91c1c", "#0ea5e9"], motif: "sand" },
  { code: "kh", nameRu: "Камбоджа", nameEn: "Cambodia", flag: "🇰🇭", region: "asia", symbol: "🛕", landmark: "Ангкор-Ват, джунгли", accent: ["#1e3a8a", "#b91c1c"], motif: "temple" },
  { code: "mv", nameRu: "Мальдивы", nameEn: "Maldives", flag: "🇲🇻", region: "asia", symbol: "🏝️", landmark: "Бирюзовые лагуны, виллы", accent: ["#0891b2", "#5eead4"], motif: "wave" },
  { code: "sa", nameRu: "Саудовская Аравия", nameEn: "Saudi Arabia", flag: "🇸🇦", region: "asia", symbol: "🕌", landmark: "Эр-Рияд, Аль-Ула, мечети", accent: ["#15803d", "#f59e0b"], motif: "sand" },
  { code: "qa", nameRu: "Катар", nameEn: "Qatar", flag: "🇶🇦", region: "asia", symbol: "🏙️", landmark: "Доха, небоскрёбы, пустыня", accent: ["#7c2d12", "#e0f2fe"], motif: "tower" },
  { code: "bh", nameRu: "Бахрейн", nameEn: "Bahrain", flag: "🇧🇭", region: "asia", symbol: "🌉", landmark: "Манама, Дерево жизни", accent: ["#dc2626", "#f8fafc"], motif: "spark" },
  { code: "kw", nameRu: "Кувейт", nameEn: "Kuwait", flag: "🇰🇼", region: "asia", symbol: "🏙️", landmark: "Кувейт-Сити, башни", accent: ["#15803d", "#f8fafc"], motif: "tower" },
  { code: "om", nameRu: "Оман", nameEn: "Oman", flag: "🇴🇲", region: "asia", symbol: "🏯", landmark: "Маскат, форты, вади", accent: ["#15803d", "#f8fafc"], motif: "sand" },
  { code: "lb", nameRu: "Ливан", nameEn: "Lebanon", flag: "🇱🇧", region: "asia", symbol: "🌲", landmark: "Бейрут, кедровые леса", accent: ["#dc2626", "#f8fafc"], motif: "leaf" },
  { code: "sy", nameRu: "Сирия", nameEn: "Syria", flag: "🇸🇾", region: "asia", symbol: "🏛️", landmark: "Дамаск, Пальмира", accent: ["#1e3a8a", "#f8fafc"], motif: "temple" },
  { code: "iq", nameRu: "Ирак", nameEn: "Iraq", flag: "🇮🇶", region: "asia", symbol: "🏛️", landmark: "Вавилон, Месопотамия", accent: ["#b91c1c", "#15803d"], motif: "temple" },
  { code: "ir", nameRu: "Иран", nameEn: "Iran", flag: "🇮🇷", region: "asia", symbol: "🕌", landmark: "Персеполь, Исфахан", accent: ["#15803d", "#f8fafc"], motif: "temple" },
  { code: "pk", nameRu: "Пакистан", nameEn: "Pakistan", flag: "🇵🇰", region: "asia", symbol: "🏔️", landmark: "Каракорум, Лахор", accent: ["#15803d", "#f8fafc"], motif: "peak" },
  { code: "bd", nameRu: "Бангладеш", nameEn: "Bangladesh", flag: "🇧🇩", region: "asia", symbol: "🌊", landmark: "Дакка, реки, мангровые леса", accent: ["#15803d", "#dc2626"], motif: "wave" },
  { code: "bt", nameRu: "Бутан", nameEn: "Bhutan", flag: "🇧🇹", region: "asia", symbol: "🏯", landmark: "Тигровое гнездо, счастье", accent: ["#ea580c", "#dc2626"], motif: "peak" },
  { code: "mm", nameRu: "Мьянма", nameEn: "Myanmar", flag: "🇲🇲", region: "asia", symbol: "🛕", landmark: "Баган, тысячи храмов", accent: ["#eab308", "#dc2626"], motif: "temple" },
  { code: "la", nameRu: "Лаос", nameEn: "Laos", flag: "🇱🇦", region: "asia", symbol: "🛕", landmark: "Луанпхабанг, водопады, Меконг", accent: ["#b91c1c", "#f59e0b"], motif: "temple" },
  { code: "bn", nameRu: "Бруней", nameEn: "Brunei", flag: "🇧🇳", region: "asia", symbol: "🕌", landmark: "Бандар-Сери-Бегаван, золотой купол", accent: ["#eab308", "#f8fafc"], motif: "temple" },
  { code: "tw", nameRu: "Тайвань", nameEn: "Taiwan", flag: "🇹🇼", region: "asia", symbol: "🏙️", landmark: "Taipei 101, уличная еда", accent: ["#1e3a8a", "#dc2626"], motif: "tower" },
  { code: "kg", nameRu: "Киргизия", nameEn: "Kyrgyzstan", flag: "🇰🇬", region: "asia", symbol: "⛰️", landmark: "Тянь-Шань, юрты, кочевники", accent: ["#dc2626", "#f8fafc"], motif: "peak" },
  { code: "tj", nameRu: "Таджикистан", nameEn: "Tajikistan", flag: "🇹🇯", region: "asia", symbol: "🏔️", landmark: "Памир, высокогорные озёра", accent: ["#15803d", "#dc2626"], motif: "peak" },
  { code: "tm", nameRu: "Туркменистан", nameEn: "Turkmenistan", flag: "🇹🇲", region: "asia", symbol: "🔥", landmark: "Ашхабад, Дарваза — врата ада", accent: ["#eab308", "#15803d"], motif: "flame" },
  { code: "af", nameRu: "Афганистан", nameEn: "Afghanistan", flag: "🇦🇫", region: "asia", symbol: "🏔️", landmark: "Бамиан, Кабул, горы Гиндукуш", accent: ["#1e3a8a", "#eab308"], motif: "peak" },
  { code: "ye", nameRu: "Йемен", nameEn: "Yemen", flag: "🇾🇪", region: "asia", symbol: "🏛️", landmark: "Сокотра, старая Сана", accent: ["#dc2626", "#f59e0b"], motif: "sand" },
  { code: "kp", nameRu: "Северная Корея", nameEn: "North Korea", flag: "🇰🇵", region: "asia", symbol: "🏛️", landmark: "Пхеньян, горы Пэктусан", accent: ["#1e3a8a", "#dc2626"], motif: "castle" },
  { code: "tl", nameRu: "Восточный Тимор", nameEn: "Timor-Leste", flag: "🇹🇱", region: "asia", symbol: "🌊", landmark: "Дили, коралловые рифы", accent: ["#dc2626", "#eab308"], motif: "wave" },

  // ─────────── NORTH AMERICA ───────────
  { code: "us", nameRu: "США", nameEn: "USA", flag: "🇺🇸", region: "north_america", symbol: "🗽", landmark: "Статуя Свободы, Нью-Йорк", accent: ["#1e3a8a", "#dc2626"], motif: "liberty" },
  { code: "ca", nameRu: "Канада", nameEn: "Canada", flag: "🇨🇦", region: "north_america", symbol: "🍁", landmark: "Ниагара, Скалистые горы", accent: ["#b91c1c", "#f8fafc"], motif: "leaf" },
  { code: "mx", nameRu: "Мексика", nameEn: "Mexico", flag: "🇲🇽", region: "north_america", symbol: "🌵", landmark: "Чичен-Ица, Канкун", accent: ["#15803d", "#dc2626"], motif: "temple" },
  { code: "cu", nameRu: "Куба", nameEn: "Cuba", flag: "🇨🇺", region: "north_america", symbol: "🚗", landmark: "Гавана, ретро-авто", accent: ["#1d4ed8", "#dc2626"], motif: "spark" },
  { code: "cr", nameRu: "Коста-Рика", nameEn: "Costa Rica", flag: "🇨🇷", region: "north_america", symbol: "🦥", landmark: "Джунгли, вулканы, ленивцы", accent: ["#15803d", "#0ea5e9"], motif: "leaf" },
  { code: "pa", nameRu: "Панама", nameEn: "Panama", flag: "🇵🇦", region: "north_america", symbol: "🚢", landmark: "Панамский канал", accent: ["#1e3a8a", "#dc2626"], motif: "wave" },
  { code: "do", nameRu: "Доминикана", nameEn: "Dominican Republic", flag: "🇩🇴", region: "north_america", symbol: "🌴", landmark: "Пунта-Кана, пляжи", accent: ["#1d4ed8", "#22d3ee"], motif: "wave" },
  { code: "jm", nameRu: "Ямайка", nameEn: "Jamaica", flag: "🇯🇲", region: "north_america", symbol: "🌴", landmark: "Регги, пляжи, водопады", accent: ["#15803d", "#eab308"], motif: "leaf" },
  { code: "gt", nameRu: "Гватемала", nameEn: "Guatemala", flag: "🇬🇹", region: "north_america", symbol: "🌋", landmark: "Майя, вулканы, Антигуа", accent: ["#0e7490", "#f59e0b"], motif: "temple" },
  { code: "bs", nameRu: "Багамы", nameEn: "Bahamas", flag: "🇧🇸", region: "north_america", symbol: "🏝️", landmark: "Нассау, голубые дыры", accent: ["#0891b2", "#5eead4"], motif: "wave" },
  { code: "bb", nameRu: "Барбадос", nameEn: "Barbados", flag: "🇧🇧", region: "north_america", symbol: "🌴", landmark: "Бриджтаун, ром, пляжи", accent: ["#1e3a8a", "#f59e0b"], motif: "wave" },
  { code: "bz", nameRu: "Белиз", nameEn: "Belize", flag: "🇧🇿", region: "north_america", symbol: "🐠", landmark: "Большой Синий Риф, руины майя", accent: ["#0e7490", "#22d3ee"], motif: "wave" },
  { code: "sv", nameRu: "Сальвадор", nameEn: "El Salvador", flag: "🇸🇻", region: "north_america", symbol: "🌋", landmark: "Санта-Ана, сёрфинг", accent: ["#1d4ed8", "#f8fafc"], motif: "wave" },
  { code: "hn", nameRu: "Гондурас", nameEn: "Honduras", flag: "🇭🇳", region: "north_america", symbol: "🏛️", landmark: "Копан, Ройатан", accent: ["#1d4ed8", "#f8fafc"], motif: "temple" },
  { code: "ni", nameRu: "Никарагуа", nameEn: "Nicaragua", flag: "🇳🇮", region: "north_america", symbol: "🌋", landmark: "Манагуа, вулканы, озёра", accent: ["#1d4ed8", "#f8fafc"], motif: "flame" },
  { code: "ht", nameRu: "Гаити", nameEn: "Haiti", flag: "🇭🇹", region: "north_america", symbol: "🏯", landmark: "Порт-о-Пренс, цитадель", accent: ["#1d4ed8", "#dc2626"], motif: "castle" },
  { code: "tt", nameRu: "Тринидад и Тобаго", nameEn: "Trinidad and Tobago", flag: "🇹🇹", region: "north_america", symbol: "🥁", landmark: "Порт-оф-Спейн, карнавал", accent: ["#dc2626", "#f59e0b"], motif: "spark" },
  { code: "ag", nameRu: "Антигуа и Барбуда", nameEn: "Antigua and Barbuda", flag: "🇦🇬", region: "north_america", symbol: "🏖️", landmark: "365 пляжей, Английская гавань", accent: ["#1e3a8a", "#f59e0b"], motif: "wave" },
  { code: "gd", nameRu: "Гренада", nameEn: "Grenada", flag: "🇬🇩", region: "north_america", symbol: "🌶️", landmark: "Остров пряностей, пляжи", accent: ["#dc2626", "#15803d"], motif: "leaf" },
  { code: "lc", nameRu: "Сент-Люсия", nameEn: "Saint Lucia", flag: "🇱🇨", region: "north_america", symbol: "🏔️", landmark: "Горы Пьетон, Кастри", accent: ["#1d4ed8", "#eab308"], motif: "peak" },
  { code: "vc", nameRu: "Сент-Винсент", nameEn: "Saint Vincent", flag: "🇻🇨", region: "north_america", symbol: "🌊", landmark: "Гренадины, пляжи", accent: ["#15803d", "#eab308"], motif: "wave" },
  { code: "kn", nameRu: "Сент-Китс и Невис", nameEn: "Saint Kitts and Nevis", flag: "🇰🇳", region: "north_america", symbol: "🏯", landmark: "Крепость Бримстон, Карибы", accent: ["#15803d", "#f8fafc"], motif: "castle" },

  // ─────────── SOUTH AMERICA ───────────
  { code: "br", nameRu: "Бразилия", nameEn: "Brazil", flag: "🇧🇷", region: "south_america", symbol: "⛪", landmark: "Рио, Христос, Амазонка", accent: ["#15803d", "#eab308"], motif: "leaf" },
  { code: "ar", nameRu: "Аргентина", nameEn: "Argentina", flag: "🇦🇷", region: "south_america", symbol: "💃", landmark: "Буэнос-Айрес, Патагония, танго", accent: ["#0ea5e9", "#f8fafc"], motif: "flame" },
  { code: "cl", nameRu: "Чили", nameEn: "Chile", flag: "🇨🇱", region: "south_america", symbol: "🏜️", landmark: "Атакама, Патагония, Пасхи", accent: ["#1e3a8a", "#dc2626"], motif: "peak" },
  { code: "pe", nameRu: "Перу", nameEn: "Peru", flag: "🇵🇪", region: "south_america", symbol: "🏔️", landmark: "Мачу-Пикчу, инки", accent: ["#b91c1c", "#15803d"], motif: "peak" },
  { code: "co", nameRu: "Колумбия", nameEn: "Colombia", flag: "🇨🇴", region: "south_america", symbol: "☕", landmark: "Картахена, кофе", accent: ["#eab308", "#dc2626"], motif: "leaf" },
  { code: "bo", nameRu: "Боливия", nameEn: "Bolivia", flag: "🇧🇴", region: "south_america", symbol: "🧂", landmark: "Солончак Уюни", accent: ["#15803d", "#e0f2fe"], motif: "snow" },
  { code: "ec", nameRu: "Эквадор", nameEn: "Ecuador", flag: "🇪🇨", region: "south_america", symbol: "🐢", landmark: "Галапагосы, экватор", accent: ["#eab308", "#1d4ed8"], motif: "leaf" },
  { code: "uy", nameRu: "Уругвай", nameEn: "Uruguay", flag: "🇺🇾", region: "south_america", symbol: "🏖️", landmark: "Монтевидео, пляжи", accent: ["#0ea5e9", "#f8fafc"], motif: "wave" },
  { code: "ve", nameRu: "Венесуэла", nameEn: "Venezuela", flag: "🇻🇪", region: "south_america", symbol: "💧", landmark: "Анхель, водопады", accent: ["#1d4ed8", "#eab308"], motif: "wave" },
  { code: "py", nameRu: "Парагвай", nameEn: "Paraguay", flag: "🇵🇾", region: "south_america", symbol: "🌿", landmark: "Асунсьон, река Парана", accent: ["#1e3a8a", "#dc2626"], motif: "leaf" },
  { code: "gy", nameRu: "Гайана", nameEn: "Guyana", flag: "🇬🇾", region: "south_america", symbol: "🌊", landmark: "Джорджтаун, водопад Кайетур", accent: ["#15803d", "#eab308"], motif: "wave" },
  { code: "sr", nameRu: "Суринам", nameEn: "Suriname", flag: "🇸🇷", region: "south_america", symbol: "🌴", landmark: "Парамарибо, тропические леса", accent: ["#15803d", "#dc2626"], motif: "leaf" },

  // ─────────── AFRICA ───────────
  { code: "eg", nameRu: "Египет", nameEn: "Egypt", flag: "🇪🇬", region: "africa", symbol: "🐫", landmark: "Пирамиды, Нил, Сфинкс", accent: ["#a16207", "#fde68a"], motif: "pyramid" },
  { code: "ma", nameRu: "Марокко", nameEn: "Morocco", flag: "🇲🇦", region: "africa", symbol: "🕌", landmark: "Марракеш, Сахара", accent: ["#9a3412", "#1d4ed8"], motif: "sand" },
  { code: "za", nameRu: "ЮАР", nameEn: "South Africa", flag: "🇿🇦", region: "africa", symbol: "🦁", landmark: "Кейптаун, сафари", accent: ["#15803d", "#eab308"], motif: "leaf" },
  { code: "tz", nameRu: "Танзания", nameEn: "Tanzania", flag: "🇹🇿", region: "africa", symbol: "🦒", landmark: "Килиманджаро, Серенгети", accent: ["#15803d", "#f59e0b"], motif: "peak" },
  { code: "ke", nameRu: "Кения", nameEn: "Kenya", flag: "🇰🇪", region: "africa", symbol: "🐘", landmark: "Масаи-Мара, сафари", accent: ["#b91c1c", "#15803d"], motif: "leaf" },
  { code: "tn", nameRu: "Тунис", nameEn: "Tunisia", flag: "🇹🇳", region: "africa", symbol: "🏜️", landmark: "Карфаген, Сахара", accent: ["#b91c1c", "#fbbf24"], motif: "sand" },
  { code: "et", nameRu: "Эфиопия", nameEn: "Ethiopia", flag: "🇪🇹", region: "africa", symbol: "☕", landmark: "Лалибэла, кофе", accent: ["#15803d", "#eab308"], motif: "leaf" },
  { code: "ng", nameRu: "Нигерия", nameEn: "Nigeria", flag: "🇳🇬", region: "africa", symbol: "🥁", landmark: "Лагос, Afrobeats", accent: ["#15803d", "#f8fafc"], motif: "spark" },
  { code: "mu", nameRu: "Маврикий", nameEn: "Mauritius", flag: "🇲🇺", region: "africa", symbol: "🏝️", landmark: "Лагуны, водопады", accent: ["#0891b2", "#5eead4"], motif: "wave" },
  { code: "sc", nameRu: "Сейшелы", nameEn: "Seychelles", flag: "🇸🇨", region: "africa", symbol: "🏖️", landmark: "Гранитные пляжи", accent: ["#0d9488", "#a7f3d0"], motif: "wave" },
  { code: "na", nameRu: "Намибия", nameEn: "Namibia", flag: "🇳🇦", region: "africa", symbol: "🏜️", landmark: "Дюны Соссусфлей", accent: ["#9a3412", "#fbbf24"], motif: "sand" },
  { code: "dz", nameRu: "Алжир", nameEn: "Algeria", flag: "🇩🇿", region: "africa", symbol: "🏜️", landmark: "Сахара, Алжир, руины Тимгад", accent: ["#15803d", "#f8fafc"], motif: "sand" },
  { code: "gh", nameRu: "Гана", nameEn: "Ghana", flag: "🇬🇭", region: "africa", symbol: "🥁", landmark: "Аккра, форты работорговли, сафари", accent: ["#dc2626", "#eab308"], motif: "spark" },
  { code: "sn", nameRu: "Сенегал", nameEn: "Senegal", flag: "🇸🇳", region: "africa", symbol: "🦅", landmark: "Дакар, остров Горе", accent: ["#15803d", "#eab308"], motif: "spark" },
  { code: "ci", nameRu: "Кот-д'Ивуар", nameEn: "Ivory Coast", flag: "🇨🇮", region: "africa", symbol: "🎺", landmark: "Абиджан, джунгли", accent: ["#ea580c", "#15803d"], motif: "leaf" },
  { code: "cm", nameRu: "Камерун", nameEn: "Cameroon", flag: "🇨🇲", region: "africa", symbol: "🦍", landmark: "Яунде, гора Камерун", accent: ["#15803d", "#dc2626"], motif: "leaf" },
  { code: "ao", nameRu: "Ангола", nameEn: "Angola", flag: "🇦🇴", region: "africa", symbol: "🌊", landmark: "Луанда, водопад Каландула", accent: ["#dc2626", "#f59e0b"], motif: "wave" },
  { code: "zw", nameRu: "Зимбабве", nameEn: "Zimbabwe", flag: "🇿🇼", region: "africa", symbol: "🌊", landmark: "Виктория, Большой Зимбабве", accent: ["#15803d", "#eab308"], motif: "wave" },
  { code: "zm", nameRu: "Замбия", nameEn: "Zambia", flag: "🇿🇲", region: "africa", symbol: "🌊", landmark: "Виктория-Фолс, национальные парки", accent: ["#15803d", "#ea580c"], motif: "wave" },
  { code: "ug", nameRu: "Уганда", nameEn: "Uganda", flag: "🇺🇬", region: "africa", symbol: "🦍", landmark: "Кампала, гориллы, Нил", accent: ["#1f2937", "#eab308"], motif: "leaf" },
  { code: "rw", nameRu: "Руанда", nameEn: "Rwanda", flag: "🇷🇼", region: "africa", symbol: "🦍", landmark: "Кигали, гориллы, тысяча холмов", accent: ["#1e3a8a", "#15803d"], motif: "peak" },
  { code: "mz", nameRu: "Мозамбик", nameEn: "Mozambique", flag: "🇲🇿", region: "africa", symbol: "🏖️", landmark: "Мапуту, острова, риф", accent: ["#eab308", "#15803d"], motif: "wave" },
  { code: "mg", nameRu: "Мадагаскар", nameEn: "Madagascar", flag: "🇲🇬", region: "africa", symbol: "🦎", landmark: "Антананариву, лемуры", accent: ["#dc2626", "#f8fafc"], motif: "leaf" },
  { code: "bw", nameRu: "Ботсвана", nameEn: "Botswana", flag: "🇧🇼", region: "africa", symbol: "🦁", landmark: "Окаванго, дельта, сафари", accent: ["#0ea5e9", "#f8fafc"], motif: "sand" },
  { code: "cv", nameRu: "Кабо-Верде", nameEn: "Cape Verde", flag: "🇨🇻", region: "africa", symbol: "🏝️", landmark: "Острова, музыка морна", accent: ["#1d4ed8", "#eab308"], motif: "wave" },
  { code: "bi", nameRu: "Бурунди", nameEn: "Burundi", flag: "🇧🇮", region: "africa", symbol: "🌿", landmark: "Бужумбура, озеро Танганьика", accent: ["#dc2626", "#15803d"], motif: "leaf" },
  { code: "ml", nameRu: "Мали", nameEn: "Mali", flag: "🇲🇱", region: "africa", symbol: "🏛️", landmark: "Тимбукту, Бамако", accent: ["#eab308", "#15803d"], motif: "sand" },
  { code: "bf", nameRu: "Буркина-Фасо", nameEn: "Burkina Faso", flag: "🇧🇫", region: "africa", symbol: "🌿", landmark: "Уагадугу, маски бобо", accent: ["#dc2626", "#15803d"], motif: "leaf" },
  { code: "ne", nameRu: "Нигер", nameEn: "Niger", flag: "🇳🇪", region: "africa", symbol: "🏜️", landmark: "Ниамей, Сахара", accent: ["#ea580c", "#15803d"], motif: "sand" },
  { code: "td", nameRu: "Чад", nameEn: "Chad", flag: "🇹🇩", region: "africa", symbol: "🏜️", landmark: "Нджамена, озеро Чад", accent: ["#1e3a8a", "#eab308"], motif: "sand" },
  { code: "sd", nameRu: "Судан", nameEn: "Sudan", flag: "🇸🇩", region: "africa", symbol: "🏛️", landmark: "Хартум, пирамиды Мероэ", accent: ["#dc2626", "#f8fafc"], motif: "pyramid" },
  { code: "ss", nameRu: "Южный Судан", nameEn: "South Sudan", flag: "🇸🇸", region: "africa", symbol: "🌿", landmark: "Джуба, река Нил", accent: ["#1f2937", "#15803d"], motif: "leaf" },
  { code: "so", nameRu: "Сомали", nameEn: "Somalia", flag: "🇸🇴", region: "africa", symbol: "🌊", landmark: "Могадишо, длинный берег", accent: ["#0ea5e9", "#f8fafc"], motif: "wave" },
  { code: "er", nameRu: "Эритрея", nameEn: "Eritrea", flag: "🇪🇷", region: "africa", symbol: "🌊", landmark: "Асмэра, Красное море", accent: ["#15803d", "#dc2626"], motif: "wave" },
  { code: "dj", nameRu: "Джибути", nameEn: "Djibouti", flag: "🇩🇯", region: "africa", symbol: "🌊", landmark: "Аддис-Абеба, Красное море", accent: ["#0ea5e9", "#15803d"], motif: "sand" },
  { code: "sz", nameRu: "Эсватини", nameEn: "Eswatini", flag: "🇸🇿", region: "africa", symbol: "🦁", landmark: "Мбабане, Хлан-Хлан", accent: ["#1d4ed8", "#eab308"], motif: "leaf" },
  { code: "ls", nameRu: "Лесото", nameEn: "Lesotho", flag: "🇱🇸", region: "africa", symbol: "⛰️", landmark: "Масеру, горное королевство", accent: ["#1d4ed8", "#f8fafc"], motif: "peak" },
  { code: "ly", nameRu: "Ливия", nameEn: "Libya", flag: "🇱🇾", region: "africa", symbol: "🏛️", landmark: "Триполи, Лептис-Магна", accent: ["#15803d", "#f8fafc"], motif: "sand" },
  { code: "mw", nameRu: "Малави", nameEn: "Malawi", flag: "🇲🇼", region: "africa", symbol: "🌊", landmark: "Лилонгве, озеро Малави", accent: ["#dc2626", "#1f2937"], motif: "wave" },
  { code: "mr", nameRu: "Мавритания", nameEn: "Mauritania", flag: "🇲🇷", region: "africa", symbol: "🏜️", landmark: "Нуакшот, Сахара, побережье", accent: ["#15803d", "#eab308"], motif: "sand" },
  { code: "gm", nameRu: "Гамбия", nameEn: "Gambia", flag: "🇬🇲", region: "africa", symbol: "🌊", landmark: "Банжул, река Гамбия, птицы", accent: ["#dc2626", "#15803d"], motif: "wave" },
  { code: "sl", nameRu: "Сьерра-Леоне", nameEn: "Sierra Leone", flag: "🇸🇱", region: "africa", symbol: "🦁", landmark: "Фритаун, пляжи", accent: ["#15803d", "#f8fafc"], motif: "leaf" },
  { code: "lr", nameRu: "Либерия", nameEn: "Liberia", flag: "🇱🇷", region: "africa", symbol: "🌿", landmark: "Монровия, тропические леса", accent: ["#dc2626", "#1e3a8a"], motif: "leaf" },
  { code: "gn", nameRu: "Гвинея", nameEn: "Guinea", flag: "🇬🇳", region: "africa", symbol: "🌊", landmark: "Конакри, водопад Шюта", accent: ["#dc2626", "#eab308"], motif: "wave" },
  { code: "gw", nameRu: "Гвинея-Бисау", nameEn: "Guinea-Bissau", flag: "🇬🇼", region: "africa", symbol: "🏝️", landmark: "Бисау, архипелаг Болама", accent: ["#eab308", "#15803d"], motif: "wave" },
  { code: "bj", nameRu: "Бенин", nameEn: "Benin", flag: "🇧🇯", region: "africa", symbol: "🏛️", landmark: "Котону, Абомейский дворец", accent: ["#eab308", "#dc2626"], motif: "temple" },
  { code: "tg", nameRu: "Того", nameEn: "Togo", flag: "🇹🇬", region: "africa", symbol: "🥁", landmark: "Ломе, вудуистские рынки", accent: ["#15803d", "#eab308"], motif: "spark" },
  { code: "cf", nameRu: "ЦАР", nameEn: "Central African Republic", flag: "🇨🇫", region: "africa", symbol: "🦍", landmark: "Банги, Дзанга-Сангха", accent: ["#15803d", "#eab308"], motif: "leaf" },
  { code: "cd", nameRu: "ДР Конго", nameEn: "DR Congo", flag: "🇨🇩", region: "africa", symbol: "🌿", landmark: "Киншаса, джунгли Конго", accent: ["#1d4ed8", "#eab308"], motif: "leaf" },
  { code: "cg", nameRu: "Конго", nameEn: "Republic of Congo", flag: "🇨🇬", region: "africa", symbol: "🌿", landmark: "Браззавиль, река Конго", accent: ["#15803d", "#f59e0b"], motif: "leaf" },
  { code: "ga", nameRu: "Габон", nameEn: "Gabon", flag: "🇬🇦", region: "africa", symbol: "🦍", landmark: "Либревиль, экватор, горилы", accent: ["#eab308", "#1e3a8a"], motif: "leaf" },
  { code: "gq", nameRu: "Экватор. Гвинея", nameEn: "Equatorial Guinea", flag: "🇬🇶", region: "africa", symbol: "🌿", landmark: "Малабо, остров Биоко", accent: ["#15803d", "#dc2626"], motif: "leaf" },
  { code: "st", nameRu: "Сан-Томе и Принсипи", nameEn: "São Tomé and Príncipe", flag: "🇸🇹", region: "africa", symbol: "🏝️", landmark: "Острова в Гвинейском заливе", accent: ["#15803d", "#eab308"], motif: "wave" },
  { code: "km", nameRu: "Коморы", nameEn: "Comoros", flag: "🇰🇲", region: "africa", symbol: "🌺", landmark: "Морони, вулкан Картала", accent: ["#0ea5e9", "#15803d"], motif: "wave" },

  // ─────────── OCEANIA ───────────
  { code: "au", nameRu: "Австралия", nameEn: "Australia", flag: "🇦🇺", region: "oceania", symbol: "🦘", landmark: "Сидней, Большой риф", accent: ["#0e7490", "#f59e0b"], motif: "wave" },
  { code: "nz", nameRu: "Новая Зеландия", nameEn: "New Zealand", flag: "🇳🇿", region: "oceania", symbol: "🏔️", landmark: "Фьорды, Средиземье", accent: ["#0f766e", "#1e3a8a"], motif: "peak" },
  { code: "fj", nameRu: "Фиджи", nameEn: "Fiji", flag: "🇫🇯", region: "oceania", symbol: "🏝️", landmark: "333 острова, лагуны", accent: ["#0891b2", "#5eead4"], motif: "wave" },
  { code: "pf", nameRu: "Фр. Полинезия", nameEn: "French Polynesia", flag: "🇵🇫", region: "oceania", symbol: "🌺", landmark: "Бора-Бора, бунгало", accent: ["#0e7490", "#fb7185"], motif: "wave" },
  { code: "ws", nameRu: "Самоа", nameEn: "Samoa", flag: "🇼🇸", region: "oceania", symbol: "🌊", landmark: "Водопады, лагуны", accent: ["#1d4ed8", "#22d3ee"], motif: "wave" },
  { code: "pg", nameRu: "Папуа — Новая Гвинея", nameEn: "Papua New Guinea", flag: "🇵🇬", region: "oceania", symbol: "🌴", landmark: "Дикие леса, племена", accent: ["#7f1d1d", "#15803d"], motif: "leaf" },
  { code: "sb", nameRu: "Соломоновы острова", nameEn: "Solomon Islands", flag: "🇸🇧", region: "oceania", symbol: "🏝️", landmark: "Хониара, лагуны, WWII", accent: ["#0ea5e9", "#22d3ee"], motif: "wave" },
  { code: "vu", nameRu: "Вануату", nameEn: "Vanuatu", flag: "🇻🇺", region: "oceania", symbol: "🌋", landmark: "Порт-Вила, вулкан Ясур", accent: ["#15803d", "#eab308"], motif: "flame" },
  { code: "to", nameRu: "Тонга", nameEn: "Tonga", flag: "🇹🇴", region: "oceania", symbol: "🐋", landmark: "Нукуалофа, горбатые киты", accent: ["#dc2626", "#f8fafc"], motif: "wave" },
  { code: "ki", nameRu: "Кирибати", nameEn: "Kiribati", flag: "🇰🇮", region: "oceania", symbol: "🏝️", landmark: "Южный Тихий океан, атоллы", accent: ["#0ea5e9", "#f8fafc"], motif: "wave" },
  { code: "fm", nameRu: "Микронезия", nameEn: "Micronesia", flag: "🇫🇲", region: "oceania", symbol: "🤿", landmark: "Паликир, подводные руины Нан-Мадол", accent: ["#0ea5e9", "#22d3ee"], motif: "wave" },
  { code: "mh", nameRu: "Маршалловы острова", nameEn: "Marshall Islands", flag: "🇲🇭", region: "oceania", symbol: "🏝️", landmark: "Маджуро, атоллы", accent: ["#1d4ed8", "#f8fafc"], motif: "wave" },
  { code: "pw", nameRu: "Палау", nameEn: "Palau", flag: "🇵🇼", region: "oceania", symbol: "🤿", landmark: "Скалистые острова, медузы", accent: ["#0891b2", "#5eead4"], motif: "wave" },
  { code: "nr", nameRu: "Науру", nameEn: "Nauru", flag: "🇳🇷", region: "oceania", symbol: "🏝️", landmark: "Ярен, фосфатный остров", accent: ["#0ea5e9", "#eab308"], motif: "wave" },
  { code: "tv", nameRu: "Тувалу", nameEn: "Tuvalu", flag: "🇹🇻", region: "oceania", symbol: "🏝️", landmark: "Фунафути, атоллы в океане", accent: ["#1d4ed8", "#22d3ee"], motif: "wave" },
  { code: "ck", nameRu: "Острова Кука", nameEn: "Cook Islands", flag: "🇨🇰", region: "oceania", symbol: "🌺", landmark: "Аваруа, лагуны, полинезия", accent: ["#0ea5e9", "#eab308"], motif: "wave" },
];

export const COUNTRIES_BY_CODE: Record<string, Country> = Object.fromEntries(
  COUNTRIES.map((c) => [c.code, c])
);
